# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 03:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('numCoins', models.DecimalField(decimal_places=4, max_digits=15)),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('buyDate', models.DateField(default=datetime.date(2018, 2, 24))),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.DecimalField(decimal_places=0, max_digits=5)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('numShares', models.DecimalField(decimal_places=0, max_digits=10)),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyDate', models.DateField(default=datetime.date(2018, 2, 24))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='crypto',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Customer'),
        ),
    ]
