# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='crypto',
            name='buyDate',
            field=models.DateField(default=datetime.date(2018, 4, 6)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buyDate',
            field=models.DateField(default=datetime.date(2018, 4, 6)),
        ),
    ]
